repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
        exclude: ^(.venv/)

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
    -   id: mypy
        exclude: ^(.venv/)

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.2.0'
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer

-   repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
    - id: isort
      name: isort (python)
